### PR TITLE
Refactor with Docusaurus and Condense Geoconnex Knowledge into one repo

### PR DESCRIPTION
**Pull request by C-Loftus**
PR Checklist
- [x] Align on layout of website and breakdown of categories
    * I generally like [https://diataxis.fr/](https://diataxis.fr/) as a style guide for making docs sites MECE. Beyond this framework, I am trying to break things down into separate sections for reference info, usage examples, tutorials for a specific goal, and background info about wider specifications
    * I want there to be one clear location for each thing a user wants to accomplish and not have overlap
- [ ] Deploy with Netlify
- [ ] Switch domain off Github pages
- [x] Transfer knowledge from existing jupyterbook
- [x] Transfer knowledge from websites outside of the docs site
- [x] Clean up and remove old assets
- [x] Design landing page and add any desired visual styling

Optional

- [ ] Add algolia search

### CODE REVIEW

**Comment by C-Loftus** [comment]
@ksonda No rush on this at all, but when you have a second, would you mind giving your initial feedback on the categorization of the sections in the site: https://deploy-preview-19--docs-geoconnex-us.netlify.app/
_(Don't worry about style / wording, I will clean that up.)_

Namely, **does "Contributing", "Querying Data", "System Architecture", and "Best Practices & Reference Info" make sense**? 

I referenced your comments when making updates: https://deploy-preview-19--docs-geoconnex-us.netlify.app/
 - I made the categories a bit terser to fit in the navbar 
 - I tried to make categories as mutually exclusive as possible so there is a clear canonical place for all info
    -   Used the word querying since it seems more specific to extracting data than "using" which might be more general
 - I wasn't sure if there is a better name for the "best practices section":
     - I agree and think it makes sense to have a separate section just for canonical data models / links to data specs, the guidance info, etc. 
     - Not sure if we should split best practices and data format reference info

**Comment by ksonda** [comment]
Nice work so far!

Let's replace "querying" with "Discover and Access" to be more normie, if wordy about it

So like

System Architecture
I want to know the technical details of how the system works

Discover and Access Data
I want to find and get water data relevant to me

Best Practices and Reference Info
I want to understand how I should curate and format my data so people can find and filter it through Geoconnex if I publish it there.

Contribute
I want Geoconnex to include my data

we can workshop it a bit with our stakeholders

**Comment by ksonda** [comment]
In the spirit of MECE I think register persistent identifiers falls under the point geoconnex to your data/ contribute data

And a third category is something about learning how geoconnex works

**Comment by C-Loftus** [comment]
Thanks for the feedback. I agree that a different category for the three points on the landing page would be more mutually exclusive, instead of having both register and upload. Since the other categories are also about learning how geoconnex works perhaps the last category could be learning about and referencing common data standards. 

Only reason I have it as it is currently is that I was trying to draw on the same icons and themes from the images you sent over. 

Do you have any preferences or desires for imagery to include on the landing page? I would be happy to explore other options

**Comment by ksonda** [comment]
colorsdheme looks fine to me for now. on the align with standards piece we can use maybe an cluster of the logos for JSON-LD/RDF like you have, the W3C logo, and the OGC logo

**Comment by C-Loftus** [comment]
Sounds good. I have brought over a significant amount of the information and organized it in the latest commit.  I ended up standardizing the colorscheme on the landing page. 

If you have any other interim feedback, feel free to let me know here or give me an ad hoc call on teams at your convenience. 

As I have been bringing in content, I have been focused on organizing it hierarchically and into discrete sections. I have generally been avoiding changing any nontrivial content. I have just been removing anything that is repetitive or rewording anything that is  overly verbose.

I will continue to clean this up, add the image your mentioned, and perhaps also add a page for a jinja templating tutorial now that i am done with that story and have a good idea for how a publisher getting started with pygeoapi would need to do it.

**Comment by C-Loftus** [comment]
@ksonda I believe I am at a good checkpoint with this.

- I have all content brought over and fixed any broken links / outdated info etc
- I believe I have all the essentials filled in so there aren't any gaps in info for the submission process end-to-end
- I've finished most of the refactoring and skeletoned out everything so there is a clean place for future content
- I have the frontpage styling filled in

Going forward
- I can create a React component to mimic the inline hoverable JSON-LD comments like you had in quarto
- I am not entirely sure how to fill in the `Access Data` section since I don't have as much experience with that side of Geconnex as an end-user.

I can continue to work more on this, merge it as is, or pause the draft PR for the time being until I get more hands on experience with geoconnex and can finish up filling in the content. 

Let me know what you prefer.

**Comment by ksonda** [comment]
Thanks @C-Loftus !

OK some feedback

1. Should the 3 main icons ont he landing page link to a corresponding section?
2. spellcheck throughout
3. https://deploy-preview-19--docs-geoconnex-us.netlify.app/category/step-2-exposing-your-data should have a bare-bones example of JSON-LD in a script header tag
4. https://deploy-preview-19--docs-geoconnex-us.netlify.app/reference/data-formats/jsonld/overview#appendices should be moved somewhere else, maybe its own page, and referenced wherever the JSON-LD element `measurementTechnique` is described

**Comment by C-Loftus** [comment]
I addressed most of the feedback and did a fair amount of refactoring. I tried to put any information regarding measurement techniques close to the JSON output where it is referenced and made a separate page for the appendix. I spent a while trying to get hoverable tooltips like we had in Quarto, but this does not seem to be currently possible in Docusaurus without writing a custom markdown parser plugin or writing a fair bit of React code, which does not seem to be practical. I could do inline comments for measurementTechnique and others if you would like or leave it as is.

https://github.com/facebook/docusaurus/discussions/10327#discussioncomment-10116424

I cut a few things out where it seemed like duplicate information (the following is described before the JSON-LD, and then it is explained again more verbosely for the same keys. So I focused on condensing things a bit).

I have been reading things over but will continue to QC before you review.

**Comment by C-Loftus** [comment]
@webb-ben before Kyle gets back and he formally reviews, perhaps you could take a look and let me know what you think? 

I have most everything cleaned up fairly well I think now. I eventually want to use https://codehike.org/ for interactive code comments / walkthroughs for JSON-LD, but until it is stable I am going to hold off.

**Review by webb-ben — COMMENTED** [review]
Looking good. Some small things I noticed as I skimmed

**Comment by webb-ben** [comment]
Another question that might be for Olivia/Paula is I thought at some point we decided to consistently reference `geoconnex.us` instead of `geoconnex`. @ksonda can you confirm

**Review by webb-ben — APPROVED** [review]

**Comment by webb-ben** [comment]
Let me know what we need to do to migrate the DNS to netlify when the time comes. @ksonda on to you

**Pull request merged**
